sudo: true

cabal: "2.4"

git:
  depth: 5

# Build only master and release tags
branches:
  only:
  - master
  - /^\d+\.\d+\.\d+(\.\d+)?$/

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.6.4
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"
    language: haskell

    install:
      - |
        curl -sSL https://get.haskellstack.org/ | sh

        stack --version
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

    script:
      - |
        stack test --system-ghc

    before_deploy:
      - |
        echo "Running before_deploy"

        stack build --system-ghc --copy-bins --local-bin-path ./artifacts"
        cp artifacts/dzen-dhall dzen-dhall
        tar -zcvf "${TRAVIS_OS_NAME}.tar.gz" dzen-dhall

    deploy:
      - provider: releases
        api_key: $API_KEY
        file:
          - ../$TRAVIS_OS_NAME.tar.gz
        skip_cleanup: true
        on:
          tags: true
        script:
          - echo 'done'

  - language: nix

    before_install:
    - sudo mkdir -p /etc/nix
    - echo "substituters = https://cache.nixos.org/ file://$HOME/nix.store" | sudo tee -a /etc/nix/nix.conf > /dev/null
    - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null

    before_script:
    - echo 'sandbox = true' | sudo tee /etc/nix/nix.conf

    script:
    - nix-build -A dzen-dhall default.nix

    before_cache:
    - mkdir -p $HOME/nix.store
    - nix copy --to file://$HOME/nix.store -f default.nix dzen-dhall

    cache:
      directories:
        - $HOME/nix.store
