name:        dzen-dhall
version:     1.0.1
synopsis:    Configure dzen2 bars in Dhall language
description: Configure dzen2 bars in Dhall language
maintainer: Kalnitsky Vladimir <klntsky@gmail.com>
license:    BSD-3-Clause
license-file: LICENSE
author: Kalnitsky Vladimir <klntsky@gmail.com>
github: dzen-dhall/dzen-dhall

extra-source-files:
- CHANGELOG.md
- README.md
- dhall/**/*.dhall

library:
  source-dirs: src
  ghc-options: -Wall

  dependencies:
  - ansi-terminal
  - prettyprinter-ansi-terminal
  - base
  - bytestring
  - dhall==1.25.0
  - directory
  - filepath
  - file-embed-lzma
  - hashable
  - hourglass
  - http-conduit
  - http-types
  - megaparsec
  - microlens
  - microlens-th
  - network-uri
  - optparse-applicative
  - parsec
  - parsers
  - pipes
  - prettyprinter
  - process
  - random
  - text
  - transformers
  - unix
  - unordered-containers
  - utf8-string
  - vector

  exposed-modules:
  - DzenDhall
  - DzenDhall.AST
  - DzenDhall.AST.Render
  - DzenDhall.Animation.Marquee
  - DzenDhall.Animation.Slider
  - DzenDhall.App
  - DzenDhall.App.Run
  - DzenDhall.App.StartingUp
  - DzenDhall.App.Forked
  - DzenDhall.Arguments
  - DzenDhall.Config
  - DzenDhall.Commands.Validate
  - DzenDhall.Commands.Plug
  - DzenDhall.Data
  - DzenDhall.Event
  - DzenDhall.Extra
  - DzenDhall.Parser
  - DzenDhall.Runtime
  - DzenDhall.Runtime.Data
  - DzenDhall.Templates
  - DzenDhall.Validation

  default-extensions: &extensions
  - DeriveFunctor
  - DeriveGeneric
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - FlexibleInstances
  - BlockArguments

  generated-other-modules:
    - Paths_dzen_dhall

executables:
  dzen-dhall:
    main: Main.hs
    source-dirs: app
    ghc-options: -Wall -threaded
    dependencies:
    - base
    - dzen-dhall

tests:
  tasty:
    default-extensions: *extensions
    main: Main.hs
    source-dirs:
    - test
    ghc-options: -Wall
    dependencies:
    - HUnit
    - QuickCheck
    - base
    - dhall==1.25.0
    - dzen-dhall
    - filepath
    - hspec
    - microlens
    - network-uri
    - optparse-applicative
    - parsec
    - tasty
    - tasty-hspec
    - tasty-hunit
    - template-haskell
    - text
    - unordered-containers
    - vector
    - generic-random
    - tasty-quickcheck
